# Generated by Django 4.2.2 on 2023-06-05 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Artist name', max_length=255)),
                ('dob', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], help_text='Gender', max_length=1)),
                ('address', models.TextField(blank=True, help_text='Artist address', null=True)),
                ('first_release_year', models.DateField(help_text='First release year')),
                ('no_of_albums_released', models.PositiveIntegerField(help_text='Number of albums released')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp', null=True)),
                ('user', models.OneToOneField(help_text='User associated with the artist', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
