# Generated by Django 4.2.2 on 2023-06-05 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('album_name', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('rnb', 'RNB'), ('country', 'Country'), ('classic', 'Classic'), ('rock', 'Rock'), ('jazz', 'Jazz')], max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('artist_relation', models.ForeignKey(help_text='Artist associated with the music', on_delete=django.db.models.deletion.CASCADE, related_name='music', to='core.artist')),
            ],
        ),
    ]
